const recipesData = [
  {
    id: 1,
    slug: "chicken-tajine-olives-lemon",
    title: "Chicken Tajine with Olives and Preserved Lemon",
    category: "Moroccan",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=1200&q=80",
    prepTime: "20 min",
    cookTime: "50 min",
    servings: 4,
    description: "Classic Moroccan chicken tajine with onion, olives, and preserved lemon.",
    ingredients: ["1 chicken cut into pieces", "2 onions sliced", "3 garlic cloves", "1 preserved lemon", "1 cup green olives", "2 tbsp olive oil", "1 tsp ginger", "1 tsp turmeric", "1 tsp black pepper", "salt", "parsley and coriander"],
    steps: ["Mix onion, garlic, herbs, olive oil, and spices in a pot or tajine.", "Add chicken and coat well with the mixture.", "Add a little water, cover, and cook on medium-low heat until tender.", "Add olives and preserved lemon and simmer 10 minutes.", "Serve hot with bread."]
  },
  {
    id: 2,
    slug: "beef-tajine-prunes",
    title: "Beef Tajine with Prunes",
    category: "Moroccan",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=80",
    prepTime: "20 min",
    cookTime: "1 hr 30 min",
    servings: 4,
    description: "Sweet and savory Moroccan tajine with tender beef and soft prunes.",
    ingredients: ["700 g beef cubes", "2 onions", "2 tbsp oil", "1 tsp ginger", "1 tsp cinnamon", "1 tsp turmeric", "salt", "pepper", "250 g prunes", "2 tbsp honey", "sesame seeds"],
    steps: ["Brown beef lightly with onions, oil, and spices.", "Add water, cover, and cook until beef is tender.", "In a small pan simmer prunes with honey and cinnamon.", "Place prunes over the cooked meat.", "Garnish with sesame seeds and serve."]
  },
  {
    id: 3,
    slug: "vegetable-couscous",
    title: "Moroccan Vegetable Couscous",
    category: "Moroccan",
    image: "https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1200&q=80",
    prepTime: "25 min",
    cookTime: "50 min",
    servings: 6,
    description: "Steamed couscous topped with a rich vegetable broth.",
    ingredients: ["500 g couscous", "2 carrots", "2 zucchini", "1 turnip", "1 onion", "1 tomato", "1 cup chickpeas", "2 tbsp olive oil", "1 tsp ginger", "1 tsp turmeric", "salt", "pepper"],
    steps: ["Cook onion, tomato, oil, and spices together for a few minutes.", "Add vegetables, chickpeas, and enough water to simmer.", "Steam couscous and fluff with a little oil or butter.", "Taste broth and adjust seasoning.", "Serve vegetables and broth over couscous."]
  },
  {
    id: 4,
    slug: "rfissa-chicken-lentils",
    title: "Rfissa with Chicken and Lentils",
    category: "Moroccan",
    image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=80",
    prepTime: "30 min",
    cookTime: "1 hr 20 min",
    servings: 6,
    description: "Traditional rfissa with shredded msemen, chicken, onions, and lentils.",
    ingredients: ["1 chicken", "4 onions sliced", "1 cup lentils", "msemen or trid pieces", "2 tbsp oil", "1 tsp ginger", "1 tsp turmeric", "fenugreek", "salt", "pepper", "parsley"],
    steps: ["Cook chicken with onions, oil, spices, and herbs.", "Add lentils and enough water and simmer until chicken is done.", "Reduce sauce until flavorful and slightly thick.", "Place shredded msemen on a serving plate.", "Top with chicken and sauce and serve hot."]
  },
  {
    id: 5,
    slug: "harira-soup",
    title: "Harira Soup",
    category: "Moroccan",
    image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=1200&q=80",
    prepTime: "20 min",
    cookTime: "50 min",
    servings: 6,
    description: "Classic Moroccan tomato soup with lentils, chickpeas, and herbs.",
    ingredients: ["1 onion", "2 tomatoes blended", "1/2 cup lentils", "1/2 cup chickpeas cooked", "celery", "parsley", "coriander", "2 tbsp flour mixed with water", "2 tbsp oil", "salt", "pepper", "ginger"],
    steps: ["Cook onion, celery, herbs, tomato, oil, and spices together.", "Add lentils and water and simmer until tender.", "Add chickpeas and continue cooking.", "Stir in flour slurry to thicken the soup.", "Serve hot with lemon wedges."]
  },
  {
    id: 6,
    slug: "zaalouk",
    title: "Zaalouk",
    category: "Moroccan",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1200&q=80",
    prepTime: "15 min",
    cookTime: "25 min",
    servings: 4,
    description: "Smoky Moroccan eggplant and tomato salad.",
    ingredients: ["2 eggplants", "2 tomatoes", "2 garlic cloves", "2 tbsp olive oil", "1 tsp paprika", "1 tsp cumin", "salt", "parsley"],
    steps: ["Cook eggplant until very soft then peel and mash.", "Cook chopped tomatoes with garlic, oil, and spices.", "Add eggplant and mash together.", "Simmer until mixture thickens.", "Serve warm or cold with bread."]
  },
  {
    id: 7,
    slug: "taktouka",
    title: "Taktouka",
    category: "Moroccan",
    image: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&w=1200&q=80",
    prepTime: "15 min",
    cookTime: "20 min",
    servings: 4,
    description: "Roasted pepper and tomato Moroccan salad.",
    ingredients: ["4 roasted peppers", "2 tomatoes", "2 garlic cloves", "2 tbsp olive oil", "1 tsp paprika", "1/2 tsp cumin", "salt"],
    steps: ["Peel and chop roasted peppers.", "Cook tomatoes with garlic, oil, and spices.", "Add peppers and cook until water evaporates.", "Mash lightly and adjust salt.", "Serve with bread."]
  },
  {
    id: 8,
    slug: "kefta-tajine-eggs",
    title: "Kefta Tajine with Eggs",
    category: "Moroccan",
    image: "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=1200&q=80",
    prepTime: "20 min",
    cookTime: "30 min",
    servings: 4,
    description: "Spiced meatballs simmered in tomato sauce and topped with eggs.",
    ingredients: ["500 g ground beef", "1 onion", "3 tomatoes", "2 garlic cloves", "4 eggs", "parsley", "cumin", "paprika", "salt", "pepper", "olive oil"],
    steps: ["Season ground beef and shape into small meatballs.", "Cook onion, tomato, garlic, oil, and spices into a sauce.", "Add meatballs and simmer until cooked through.", "Crack eggs over the sauce.", "Cover briefly until eggs set and serve."]
  },
  {
    id: 9,
    slug: "bissara",
    title: "Bissara",
    category: "Moroccan",
    image: "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=1200&q=80",
    prepTime: "10 min",
    cookTime: "45 min",
    servings: 4,
    description: "Creamy fava bean soup served with olive oil and cumin.",
    ingredients: ["300 g dried split fava beans", "3 garlic cloves", "olive oil", "1 tsp cumin", "salt", "water"],
    steps: ["Boil beans with garlic and water until very soft.", "Blend or mash until smooth.", "Season with salt and cumin.", "Warm through if needed.", "Serve with olive oil on top."]
  },
  {
    id: 10,
    slug: "chermoula-sardines",
    title: "Chermoula Sardines",
    category: "Moroccan",
    image: "https://images.unsplash.com/photo-1510130387422-82bed34b37e9?auto=format&fit=crop&w=1200&q=80",
    prepTime: "20 min",
    cookTime: "15 min",
    servings: 4,
    description: "Sardines marinated in chermoula and baked or fried.",
    ingredients: ["500 g sardine fillets", "parsley", "coriander", "3 garlic cloves", "1 tsp paprika", "1 tsp cumin", "lemon juice", "olive oil", "salt"],
    steps: ["Mix herbs, garlic, spices, lemon juice, and oil to make chermoula.", "Coat sardines well in the marinade.", "Rest for 15 minutes if possible.", "Bake or fry until cooked.", "Serve with lemon."]
  },
  {
    id: 11,
    slug: "lentil-salad",
    title: "Lentil Salad",
    category: "Healthy",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1200&q=80",
    prepTime: "15 min",
    cookTime: "20 min",
    servings: 4,
    description: "Protein-rich lentil salad with herbs and lemon.",
    ingredients: ["1 cup lentils", "1 cucumber", "2 tomatoes", "parsley", "olive oil", "lemon juice", "salt", "pepper"],
    steps: ["Cook lentils until tender and cool.", "Chop vegetables and herbs.", "Mix everything in a bowl.", "Season with oil, lemon, salt, and pepper.", "Serve chilled or at room temperature."]
  },
  {
    id: 12,
    slug: "quinoa-bowl",
    title: "Quinoa Veggie Bowl",
    category: "Healthy",
    image: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1200&q=80",
    prepTime: "15 min",
    cookTime: "20 min",
    servings: 2,
    description: "Balanced bowl with quinoa, roasted vegetables, and chickpeas.",
    ingredients: ["1 cup quinoa", "1 zucchini", "1 carrot", "1 cup chickpeas", "olive oil", "paprika", "salt", "lemon dressing"],
    steps: ["Cook quinoa according to package directions.", "Roast chopped vegetables and chickpeas with oil and paprika.", "Arrange quinoa in bowls.", "Top with roasted vegetables.", "Finish with lemon dressing."]
  },
  {
    id: 13,
    slug: "avocado-toast",
    title: "Avocado Toast",
    category: "Breakfast",
    image: "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=1200&q=80",
    prepTime: "10 min",
    cookTime: "5 min",
    servings: 2,
    description: "Quick breakfast toast with mashed avocado and lemon.",
    ingredients: ["2 slices bread", "1 avocado", "lemon juice", "salt", "pepper", "chili flakes optional"],
    steps: ["Toast the bread.", "Mash avocado with lemon juice, salt, and pepper.", "Spread on toast.", "Add chili flakes if desired.", "Serve immediately."]
  },
  {
    id: 14,
    slug: "greek-salad",
    title: "Greek Salad",
    category: "Healthy",
    image: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&w=1200&q=80",
    prepTime: "15 min",
    cookTime: "0 min",
    servings: 4,
    description: "Fresh cucumber, tomato, olives, and feta salad.",
    ingredients: ["2 tomatoes", "1 cucumber", "1/2 onion", "feta cheese", "olives", "olive oil", "oregano", "salt"],
    steps: ["Chop vegetables.", "Place in a bowl with olives and feta.", "Drizzle with olive oil.", "Season with oregano and a little salt.", "Serve fresh."]
  },
  {
    id: 15,
    slug: "grilled-chicken-salad",
    title: "Grilled Chicken Salad",
    category: "Healthy",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1200&q=80",
    prepTime: "15 min",
    cookTime: "15 min",
    servings: 2,
    description: "Light salad topped with grilled chicken breast.",
    ingredients: ["2 chicken breasts", "lettuce", "cherry tomatoes", "cucumber", "olive oil", "lemon juice", "salt", "pepper"],
    steps: ["Season and grill chicken until cooked.", "Slice chicken into strips.", "Prepare salad vegetables in a bowl.", "Top with chicken.", "Dress with oil and lemon."]
  },
  {
    id: 16,
    slug: "vegetable-soup",
    title: "Vegetable Soup",
    category: "Healthy",
    image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=1200&q=80",
    prepTime: "15 min",
    cookTime: "30 min",
    servings: 4,
    description: "Simple everyday vegetable soup.",
    ingredients: ["1 onion", "2 carrots", "1 zucchini", "1 potato", "2 tbsp oil", "salt", "pepper", "water or stock"],
    steps: ["Sauté onion in oil.", "Add chopped vegetables.", "Pour in stock and simmer until soft.", "Blend if desired or leave chunky.", "Season and serve hot."]
  },
  {
    id: 17,
    slug: "oatmeal-fruit-bowl",
    title: "Oatmeal Fruit Bowl",
    category: "Breakfast",
    image: "https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1200&q=80",
    prepTime: "5 min",
    cookTime: "10 min",
    servings: 2,
    description: "Warm oats with fruit and honey.",
    ingredients: ["1 cup oats", "2 cups milk or water", "banana", "berries", "honey", "cinnamon"],
    steps: ["Cook oats with milk or water until creamy.", "Pour into bowls.", "Top with sliced fruit.", "Add honey and cinnamon.", "Serve warm."]
  },
  {
    id: 18,
    slug: "chickpea-salad",
    title: "Chickpea Salad",
    category: "Healthy",
    image: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&w=1200&q=80",
    prepTime: "10 min",
    cookTime: "0 min",
    servings: 4,
    description: "Quick salad with chickpeas, herbs, and lemon.",
    ingredients: ["2 cups cooked chickpeas", "1 tomato", "1 cucumber", "parsley", "olive oil", "lemon juice", "salt", "pepper"],
    steps: ["Rinse chickpeas and place in a bowl.", "Add chopped vegetables and parsley.", "Dress with oil and lemon.", "Season well.", "Serve chilled."]
  },
  {
    id: 19,
    slug: "fruit-smoothie",
    title: "Banana Berry Smoothie",
    category: "Drinks",
    image: "https://images.unsplash.com/photo-1502741338009-cac2772e18bc?auto=format&fit=crop&w=1200&q=80",
    prepTime: "5 min",
    cookTime: "0 min",
    servings: 2,
    description: "Refreshing smoothie for breakfast or snack.",
    ingredients: ["1 banana", "1 cup berries", "1 cup yogurt or milk", "1 tsp honey"],
    steps: ["Put all ingredients into a blender.", "Blend until smooth.", "Taste and adjust sweetness.", "Pour into glasses.", "Serve cold."]
  },
  {
    id: 20,
    slug: "stuffed-bell-peppers",
    title: "Stuffed Bell Peppers",
    category: "Healthy",
    image: "https://images.unsplash.com/photo-1543332164-6e82f355badc?auto=format&fit=crop&w=1200&q=80",
    prepTime: "20 min",
    cookTime: "35 min",
    servings: 4,
    description: "Bell peppers stuffed with rice and vegetables.",
    ingredients: ["4 bell peppers", "1 cup cooked rice", "1 onion", "1 carrot", "1 zucchini", "olive oil", "salt", "pepper"],
    steps: ["Cut tops off peppers and remove seeds.", "Cook onion and vegetables in oil.", "Mix with rice and seasoning.", "Stuff peppers and place in baking dish.", "Bake until peppers soften."]
  },
  {
    id: 21,
    slug: "spaghetti-bolognese",
    title: "Spaghetti Bolognese",
    category: "Italian",
    image: "https://images.unsplash.com/photo-1622973536968-3ead9e780960?auto=format&fit=crop&w=1200&q=80",
    prepTime: "15 min",
    cookTime: "35 min",
    servings: 4,
    description: "Classic pasta with rich meat and tomato sauce.",
    ingredients: ["300 g spaghetti", "300 g ground beef", "1 onion", "2 garlic cloves", "400 g tomato sauce", "olive oil", "salt", "pepper"],
    steps: ["Cook spaghetti until al dente.", "Sauté onion and garlic in oil.", "Add beef and cook until browned.", "Pour in tomato sauce and simmer.", "Serve sauce over spaghetti."]
  },
  {
    id: 22,
    slug: "creamy-mushroom-pasta",
    title: "Creamy Mushroom Pasta",
    category: "Italian",
    image: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1200&q=80",
    prepTime: "10 min",
    cookTime: "20 min",
    servings: 4,
    description: "Creamy pasta with mushrooms and garlic.",
    ingredients: ["300 g pasta", "250 g mushrooms", "2 garlic cloves", "200 ml cream", "parmesan", "olive oil", "salt", "pepper"],
    steps: ["Cook pasta and reserve a little water.", "Cook mushrooms and garlic in oil.", "Add cream and parmesan.", "Combine with pasta.", "Adjust with pasta water and serve."]
  },
  {
    id: 23,
    slug: "lasagna",
    title: "Beef Lasagna",
    category: "Italian",
    image: "https://images.unsplash.com/photo-1619895092538-128341789043?auto=format&fit=crop&w=1200&q=80",
    prepTime: "25 min",
    cookTime: "45 min",
    servings: 6,
    description: "Layered lasagna with meat sauce and béchamel.",
    ingredients: ["lasagna sheets", "400 g ground beef", "1 onion", "tomato sauce", "béchamel sauce", "mozzarella", "olive oil", "salt"],
    steps: ["Cook beef with onion and tomato sauce.", "Spread a little sauce in a baking dish.", "Layer pasta, meat sauce, béchamel, and cheese.", "Repeat layers and finish with cheese.", "Bake until golden."]
  },
  {
    id: 24,
    slug: "margherita-pizza",
    title: "Margherita Pizza",
    category: "Italian",
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=1200&q=80",
    prepTime: "20 min",
    cookTime: "15 min",
    servings: 4,
    description: "Simple pizza with tomato, mozzarella, and basil.",
    ingredients: ["pizza dough", "tomato sauce", "mozzarella", "basil", "olive oil"],
    steps: ["Roll out the dough.", "Spread with tomato sauce.", "Add mozzarella pieces.", "Bake in a hot oven until crust is done.", "Top with basil and a little oil."]
  },
  {
    id: 25,
    slug: "risotto-mushroom",
    title: "Mushroom Risotto",
    category: "Italian",
    image: "https://images.unsplash.com/photo-1476124369491-e7addf5db371?auto=format&fit=crop&w=1200&q=80",
    prepTime: "15 min",
    cookTime: "30 min",
    servings: 4,
    description: "Creamy risotto with mushrooms and parmesan.",
    ingredients: ["1 cup arborio rice", "250 g mushrooms", "1 onion", "4 cups warm stock", "parmesan", "butter", "olive oil"],
    steps: ["Cook onion in oil and butter.", "Add rice and stir briefly.", "Add stock little by little while stirring.", "Cook mushrooms separately and fold in.", "Finish with parmesan and serve."]
  },
  {
    id: 26,
    slug: "alfredo-pasta",
    title: "Chicken Alfredo Pasta",
    category: "Italian",
    image: "https://images.unsplash.com/photo-1516100882582-96c3a05fe590?auto=format&fit=crop&w=1200&q=80",
    prepTime: "15 min",
    cookTime: "20 min",
    servings: 4,
    description: "Creamy Alfredo sauce with chicken and pasta.",
    ingredients: ["300 g fettuccine", "2 chicken breasts", "200 ml cream", "parmesan", "2 garlic cloves", "butter", "salt", "pepper"],
    steps: ["Cook pasta.", "Cook seasoned chicken and slice.", "Make sauce with butter, garlic, cream, and parmesan.", "Add pasta and chicken to sauce.", "Serve hot."]
  },
  {
    id: 27,
    slug: "bruschetta",
    title: "Tomato Bruschetta",
    category: "Italian",
    image: "https://images.unsplash.com/photo-1506280754576-f6fa8a873550?auto=format&fit=crop&w=1200&q=80",
    prepTime: "10 min",
    cookTime: "5 min",
    servings: 4,
    description: "Toasted bread topped with tomato and basil.",
    ingredients: ["baguette slices", "2 tomatoes", "basil", "1 garlic clove", "olive oil", "salt"],
    steps: ["Toast bread slices.", "Rub with garlic.", "Mix chopped tomatoes with basil and oil.", "Spoon over toast.", "Serve immediately."]
  },
  {
    id: 28,
    slug: "gnocchi-tomato",
    title: "Gnocchi with Tomato Sauce",
    category: "Italian",
    image: "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=1200&q=80",
    prepTime: "10 min",
    cookTime: "15 min",
    servings: 4,
    description: "Soft gnocchi in simple tomato sauce.",
    ingredients: ["500 g gnocchi", "tomato sauce", "1 garlic clove", "olive oil", "parmesan", "basil"],
    steps: ["Cook gnocchi according to package directions.", "Warm tomato sauce with garlic and oil.", "Add cooked gnocchi to the sauce.", "Top with parmesan and basil.", "Serve hot."]
  },
  {
    id: 29,
    slug: "caprese-salad",
    title: "Caprese Salad",
    category: "Italian",
    image: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&w=1200&q=80",
    prepTime: "10 min",
    cookTime: "0 min",
    servings: 2,
    description: "Fresh tomato, mozzarella, and basil salad.",
    ingredients: ["2 tomatoes", "mozzarella", "basil", "olive oil", "salt", "pepper"],
    steps: ["Slice tomato and mozzarella.", "Arrange on a plate.", "Add basil leaves.", "Drizzle with oil.", "Season and serve."]
  },
  {
    id: 30,
    slug: "minestrone",
    title: "Minestrone Soup",
    category: "Italian",
    image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=1200&q=80",
    prepTime: "15 min",
    cookTime: "30 min",
    servings: 6,
    description: "Hearty Italian vegetable soup with beans and pasta.",
    ingredients: ["1 onion", "2 carrots", "2 celery stalks", "1 zucchini", "1 cup beans", "small pasta", "tomato", "stock", "olive oil"],
    steps: ["Cook onion, carrot, and celery in oil.", "Add remaining vegetables and stock.", "Simmer until vegetables soften.", "Add beans and pasta.", "Cook until pasta is tender and serve."]
  },
  {
    id: 31,
    slug: "beef-burger",
    title: "Classic Beef Burger",
    category: "Fast Food",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=1200&q=80",
    prepTime: "15 min",
    cookTime: "10 min",
    servings: 4,
    description: "Juicy homemade beef burgers.",
    ingredients: ["500 g ground beef", "burger buns", "lettuce", "tomato", "cheese slices", "salt", "pepper"],
    steps: ["Season beef and shape patties.", "Cook patties in a pan or on a grill.", "Toast buns lightly.", "Assemble buns with burger, vegetables, and cheese.", "Serve warm."]
  },
  {
    id: 32,
    slug: "crispy-chicken-burger",
    title: "Crispy Chicken Burger",
    category: "Fast Food",
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=1200&q=80",
    prepTime: "20 min",
    cookTime: "15 min",
    servings: 4,
    description: "Breaded chicken burger with lettuce and sauce.",
    ingredients: ["2 chicken breasts", "flour", "egg", "breadcrumbs", "burger buns", "lettuce", "mayonnaise", "salt", "pepper"],
    steps: ["Flatten and season chicken pieces.", "Coat in flour, egg, then breadcrumbs.", "Fry until golden and cooked through.", "Assemble in buns with lettuce and sauce.", "Serve hot."]
  },
  {
    id: 33,
    slug: "chicken-wrap",
    title: "Chicken Wrap",
    category: "Fast Food",
    image: "https://images.unsplash.com/photo-1530469912745-a215c6b256ea?auto=format&fit=crop&w=1200&q=80",
    prepTime: "15 min",
    cookTime: "10 min",
    servings: 4,
    description: "Soft tortilla wrap with chicken and fresh vegetables.",
    ingredients: ["4 tortillas", "2 chicken breasts", "lettuce", "tomato", "yogurt sauce", "salt", "pepper"],
    steps: ["Cook seasoned chicken and slice.", "Warm tortillas.", "Fill with lettuce, tomato, and chicken.", "Add sauce.", "Roll and serve."]
  },
  {
    id: 34,
    slug: "shawarma-wrap",
    title: "Chicken Shawarma Wrap",
    category: "Fast Food",
    image: "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&w=1200&q=80",
    prepTime: "20 min",
    cookTime: "15 min",
    servings: 4,
    description: "Spiced chicken strips wrapped in flatbread.",
    ingredients: ["500 g chicken strips", "shawarma spices", "yogurt", "flatbread", "lettuce", "tomato", "garlic sauce"],
    steps: ["Marinate chicken with spices and yogurt.", "Cook in a hot pan until done.", "Warm bread.", "Fill with chicken, vegetables, and sauce.", "Roll tightly and serve."]
  },
  {
    id: 35,
    slug: "homemade-fries",
    title: "Homemade Fries",
    category: "Fast Food",
    image: "https://images.unsplash.com/photo-1576107232684-1279f390859f?auto=format&fit=crop&w=1200&q=80",
    prepTime: "10 min",
    cookTime: "20 min",
    servings: 4,
    description: "Crispy potato fries made at home.",
    ingredients: ["4 potatoes", "oil", "salt"],
    steps: ["Cut potatoes into strips.", "Soak briefly and dry well.", "Fry or bake until crisp.", "Drain excess oil if fried.", "Season with salt and serve."]
  },
  {
    id: 36,
    slug: "club-sandwich",
    title: "Club Sandwich",
    category: "Fast Food",
    image: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=1200&q=80",
    prepTime: "15 min",
    cookTime: "10 min",
    servings: 2,
    description: "Layered sandwich with chicken, lettuce, and tomato.",
    ingredients: ["6 slices toast bread", "chicken breast", "lettuce", "tomato", "mayonnaise", "cheese"],
    steps: ["Cook chicken and slice thinly.", "Toast bread lightly.", "Layer bread, mayonnaise, lettuce, tomato, cheese, and chicken.", "Repeat layers.", "Cut and serve."]
  },
  {
    id: 37,
    slug: "hot-dog",
    title: "Hot Dog",
    category: "Fast Food",
    image: "https://images.unsplash.com/photo-1612392062798-4a3b6bd6d4e9?auto=format&fit=crop&w=1200&q=80",
    prepTime: "10 min",
    cookTime: "10 min",
    servings: 4,
    description: "Simple hot dog with your favorite toppings.",
    ingredients: ["4 hot dog buns", "4 sausages", "mustard", "ketchup", "onion optional"],
    steps: ["Cook sausages.", "Warm buns.", "Place sausage inside each bun.", "Add sauces and toppings.", "Serve hot."]
  },
  {
    id: 38,
    slug: "fried-chicken-strips",
    title: "Fried Chicken Strips",
    category: "Fast Food",
    image: "https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=1200&q=80",
    prepTime: "20 min",
    cookTime: "15 min",
    servings: 4,
    description: "Crunchy chicken strips perfect for dipping.",
    ingredients: ["500 g chicken strips", "flour", "egg", "breadcrumbs", "salt", "pepper", "paprika"],
    steps: ["Season chicken.", "Dip in flour, egg, and breadcrumbs.", "Fry until golden and cooked through.", "Drain on paper.", "Serve with sauce."]
  },
  {
    id: 39,
    slug: "quesadilla-cheese",
    title: "Cheese Quesadilla",
    category: "Fast Food",
    image: "https://images.unsplash.com/photo-1618040996337-56904b7850b9?auto=format&fit=crop&w=1200&q=80",
    prepTime: "10 min",
    cookTime: "8 min",
    servings: 2,
    description: "Quick tortilla filled with melted cheese.",
    ingredients: ["2 tortillas", "grated cheese", "butter"],
    steps: ["Place cheese on one tortilla and top with another.", "Cook in a pan with a little butter.", "Flip once until both sides are golden.", "Slice into wedges.", "Serve warm."]
  },
  {
    id: 40,
    slug: "loaded-nachos",
    title: "Loaded Nachos",
    category: "Fast Food",
    image: "https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?auto=format&fit=crop&w=1200&q=80",
    prepTime: "10 min",
    cookTime: "10 min",
    servings: 4,
    description: "Nachos topped with cheese, beans, and salsa.",
    ingredients: ["nacho chips", "grated cheese", "beans", "salsa", "jalapeños optional"],
    steps: ["Spread chips on a tray.", "Top with beans and cheese.", "Bake until cheese melts.", "Add salsa and jalapeños.", "Serve immediately."]
  },
  {
    id: 41,
    slug: "pancakes",
    title: "Fluffy Pancakes",
    category: "Dessert",
    image: "https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1200&q=80",
    prepTime: "10 min",
    cookTime: "15 min",
    servings: 4,
    description: "Soft fluffy pancakes for breakfast or dessert.",
    ingredients: ["1 cup flour", "1 egg", "1 cup milk", "1 tbsp sugar", "1 tsp baking powder", "butter"],
    steps: ["Mix dry ingredients.", "Whisk in egg and milk.", "Cook spoonfuls in a buttered pan.", "Flip when bubbles appear.", "Serve with honey or fruit."]
  },
  {
    id: 42,
    slug: "chocolate-cake",
    title: "Chocolate Cake",
    category: "Dessert",
    image: "https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&w=1200&q=80",
    prepTime: "20 min",
    cookTime: "35 min",
    servings: 8,
    description: "Moist chocolate cake with deep cocoa flavor.",
    ingredients: ["2 cups flour", "1 cup sugar", "1/2 cup cocoa powder", "2 eggs", "1 cup milk", "1/2 cup oil", "1 tsp baking powder"],
    steps: ["Mix dry ingredients in a bowl.", "Add eggs, milk, and oil.", "Pour into a greased pan.", "Bake until a skewer comes out clean.", "Cool before serving."]
  },
  {
    id: 43,
    slug: "apple-pie",
    title: "Apple Pie",
    category: "Dessert",
    image: "https://images.unsplash.com/photo-1568571780765-9276ac8b75a2?auto=format&fit=crop&w=1200&q=80",
    prepTime: "25 min",
    cookTime: "40 min",
    servings: 8,
    description: "Classic apple pie with cinnamon filling.",
    ingredients: ["pie dough", "4 apples", "sugar", "cinnamon", "butter", "1 egg for brushing"],
    steps: ["Slice apples and mix with sugar and cinnamon.", "Line a pie dish with dough.", "Add apple filling.", "Cover with top crust and brush with egg.", "Bake until golden."]
  },
  {
    id: 44,
    slug: "vanilla-cupcakes",
    title: "Vanilla Cupcakes",
    category: "Dessert",
    image: "https://images.unsplash.com/photo-1486427944299-d1955d23e34d?auto=format&fit=crop&w=1200&q=80",
    prepTime: "15 min",
    cookTime: "18 min",
    servings: 12,
    description: "Light cupcakes with vanilla flavor.",
    ingredients: ["1 1/2 cups flour", "2 eggs", "3/4 cup sugar", "1/2 cup butter", "1/2 cup milk", "vanilla", "1 tsp baking powder"],
    steps: ["Cream butter and sugar.", "Add eggs and vanilla.", "Fold in flour, baking powder, and milk.", "Divide into cupcake cases.", "Bake until lightly golden."]
  },
  {
    id: 45,
    slug: "brownies",
    title: "Chocolate Brownies",
    category: "Dessert",
    image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=1200&q=80",
    prepTime: "15 min",
    cookTime: "25 min",
    servings: 9,
    description: "Fudgy chocolate brownies.",
    ingredients: ["200 g dark chocolate", "100 g butter", "2 eggs", "3/4 cup sugar", "1/2 cup flour"],
    steps: ["Melt chocolate and butter.", "Whisk eggs with sugar.", "Mix in chocolate mixture and flour.", "Pour into a pan.", "Bake until just set."]
  },
  {
    id: 46,
    slug: "rice-pudding",
    title: "Rice Pudding",
    category: "Dessert",
    image: "https://images.unsplash.com/photo-1511690656952-34342bb7c2f2?auto=format&fit=crop&w=1200&q=80",
    prepTime: "5 min",
    cookTime: "30 min",
    servings: 4,
    description: "Creamy rice pudding flavored with cinnamon.",
    ingredients: ["1/2 cup rice", "3 cups milk", "sugar", "cinnamon", "vanilla optional"],
    steps: ["Cook rice with milk over low heat.", "Stir often until creamy.", "Sweeten to taste.", "Pour into bowls.", "Top with cinnamon."]
  },
  {
    id: 47,
    slug: "lemon-tart",
    title: "Lemon Tart",
    category: "Dessert",
    image: "https://images.unsplash.com/photo-1519915028121-7d3463d5b1c1?auto=format&fit=crop&w=1200&q=80",
    prepTime: "20 min",
    cookTime: "30 min",
    servings: 8,
    description: "Tangy lemon tart with smooth filling.",
    ingredients: ["tart crust", "2 lemons", "3 eggs", "3/4 cup sugar", "butter"],
    steps: ["Bake tart crust until lightly golden.", "Whisk lemon juice, eggs, and sugar.", "Cook gently with butter until thick.", "Pour into crust.", "Chill before serving."]
  },
  {
    id: 48,
    slug: "banana-bread",
    title: "Banana Bread",
    category: "Dessert",
    image: "https://images.unsplash.com/photo-1605286978633-2dec93ff88a2?auto=format&fit=crop&w=1200&q=80",
    prepTime: "15 min",
    cookTime: "45 min",
    servings: 8,
    description: "Soft loaf made with ripe bananas.",
    ingredients: ["3 ripe bananas", "2 eggs", "1/2 cup sugar", "1/2 cup oil or butter", "1 1/2 cups flour", "1 tsp baking powder"],
    steps: ["Mash bananas.", "Mix with eggs, sugar, and oil.", "Fold in flour and baking powder.", "Pour into loaf pan.", "Bake until cooked through."]
  },
  {
    id: 49,
    slug: "donuts",
    title: "Glazed Donuts",
    category: "Dessert",
    image: "https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&w=1200&q=80",
    prepTime: "25 min",
    cookTime: "15 min",
    servings: 12,
    description: "Soft donuts topped with sweet glaze.",
    ingredients: ["2 cups flour", "1 egg", "1/2 cup milk", "2 tbsp sugar", "1 tsp yeast", "oil for frying", "icing sugar"],
    steps: ["Prepare a soft dough and let it rise.", "Cut donut shapes.", "Fry until golden.", "Drain well.", "Dip in glaze and let set."]
  },
  {
    id: 50,
    slug: "fruit-tart",
    title: "Fruit Tart",
    category: "Dessert",
    image: "https://images.unsplash.com/photo-1464306076886-da185f6a9d05?auto=format&fit=crop&w=1200&q=80",
    prepTime: "25 min",
    cookTime: "20 min",
    servings: 8,
    description: "Pastry tart topped with cream and fresh fruit.",
    ingredients: ["tart crust", "pastry cream", "strawberries", "kiwi", "berries"],
    steps: ["Bake tart crust and cool.", "Fill with chilled pastry cream.", "Arrange fruit on top.", "Chill until ready.", "Serve cold."]
  },
  {
    id: 51,
    slug: "scrambled-eggs",
    title: "Scrambled Eggs",
    category: "Breakfast",
    image: "https://images.unsplash.com/photo-1482049016688-2d3e1b311543?auto=format&fit=crop&w=1200&q=80",
    prepTime: "5 min",
    cookTime: "5 min",
    servings: 2,
    description: "Soft creamy scrambled eggs.",
    ingredients: ["4 eggs", "1 tbsp butter", "salt", "pepper"],
    steps: ["Whisk eggs with salt.", "Melt butter in a pan.", "Cook eggs gently while stirring.", "Remove when softly set.", "Serve immediately."]
  },
  {
    id: 52,
    slug: "omelette-cheese",
    title: "Cheese Omelette",
    category: "Breakfast",
    image: "https://images.unsplash.com/photo-1510693206972-df098062cb71?auto=format&fit=crop&w=1200&q=80",
    prepTime: "5 min",
    cookTime: "7 min",
    servings: 2,
    description: "Quick omelette with melting cheese.",
    ingredients: ["4 eggs", "grated cheese", "butter", "salt", "pepper"],
    steps: ["Beat eggs with salt and pepper.", "Pour into buttered pan.", "Add cheese when nearly set.", "Fold omelette in half.", "Serve warm."]
  },
  {
    id: 53,
    slug: "french-toast",
    title: "French Toast",
    category: "Breakfast",
    image: "https://images.unsplash.com/photo-1484723091739-30a097e8f929?auto=format&fit=crop&w=1200&q=80",
    prepTime: "10 min",
    cookTime: "10 min",
    servings: 2,
    description: "Bread dipped in egg and milk then pan fried.",
    ingredients: ["4 bread slices", "2 eggs", "1/2 cup milk", "1 tbsp sugar", "butter", "cinnamon optional"],
    steps: ["Whisk eggs, milk, and sugar.", "Dip bread slices briefly.", "Cook in buttered pan until golden.", "Flip and cook other side.", "Serve with honey or fruit."]
  },
  {
    id: 54,
    slug: "shakshuka",
    title: "Shakshuka",
    category: "Breakfast",
    image: "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=1200&q=80",
    prepTime: "10 min",
    cookTime: "20 min",
    servings: 4,
    description: "Eggs poached in a spiced tomato sauce.",
    ingredients: ["4 eggs", "1 onion", "3 tomatoes", "1 pepper", "olive oil", "paprika", "salt", "pepper"],
    steps: ["Cook onion and pepper in oil.", "Add chopped tomatoes and spices.", "Simmer into a thick sauce.", "Crack eggs into the sauce.", "Cover until eggs are set."]
  },
  {
    id: 55,
    slug: "chia-pudding",
    title: "Chia Pudding",
    category: "Breakfast",
    image: "https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?auto=format&fit=crop&w=1200&q=80",
    prepTime: "5 min",
    cookTime: "0 min",
    servings: 2,
    description: "Overnight chia pudding with fruit topping.",
    ingredients: ["1/4 cup chia seeds", "1 cup milk", "1 tsp honey", "fruit"],
    steps: ["Mix chia seeds, milk, and honey.", "Refrigerate several hours or overnight.", "Stir once if needed.", "Top with fruit.", "Serve cold."]
  },
  {
    id: 56,
    slug: "granola-yogurt-parfait",
    title: "Granola Yogurt Parfait",
    category: "Breakfast",
    image: "https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=1200&q=80",
    prepTime: "5 min",
    cookTime: "0 min",
    servings: 2,
    description: "Yogurt layered with granola and fruit.",
    ingredients: ["2 cups yogurt", "granola", "berries", "honey"],
    steps: ["Spoon yogurt into glasses.", "Add a layer of granola.", "Top with fruit.", "Repeat layers if desired.", "Drizzle with honey."]
  },
  {
    id: 57,
    slug: "bagel-cream-cheese",
    title: "Bagel with Cream Cheese",
    category: "Breakfast",
    image: "https://images.unsplash.com/photo-1608198093002-ad4e005484ec?auto=format&fit=crop&w=1200&q=80",
    prepTime: "5 min",
    cookTime: "3 min",
    servings: 2,
    description: "Simple breakfast bagel with cream cheese.",
    ingredients: ["2 bagels", "cream cheese", "cucumber or tomato optional"],
    steps: ["Slice and toast bagels.", "Spread with cream cheese.", "Add toppings if desired.", "Close or serve open.", "Enjoy warm."]
  },
  {
    id: 58,
    slug: "egg-muffins",
    title: "Egg Muffins",
    category: "Breakfast",
    image: "https://images.unsplash.com/photo-1482049016688-2d3e1b311543?auto=format&fit=crop&w=1200&q=80",
    prepTime: "10 min",
    cookTime: "18 min",
    servings: 6,
    description: "Mini baked eggs with vegetables.",
    ingredients: ["6 eggs", "bell pepper", "spinach", "cheese", "salt", "pepper"],
    steps: ["Whisk eggs with seasoning.", "Add chopped vegetables and cheese.", "Pour into muffin cups.", "Bake until set.", "Serve warm."]
  },
  {
    id: 59,
    slug: "smoothie-bowl",
    title: "Smoothie Bowl",
    category: "Breakfast",
    image: "https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?auto=format&fit=crop&w=1200&q=80",
    prepTime: "10 min",
    cookTime: "0 min",
    servings: 2,
    description: "Thick smoothie topped with fruit and seeds.",
    ingredients: ["banana", "berries", "yogurt", "granola", "chia seeds"],
    steps: ["Blend banana, berries, and yogurt until thick.", "Pour into bowls.", "Top with granola and seeds.", "Add sliced fruit.", "Serve immediately."]
  },
  {
    id: 60,
    slug: "breakfast-burrito",
    title: "Breakfast Burrito",
    category: "Breakfast",
    image: "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&w=1200&q=80",
    prepTime: "10 min",
    cookTime: "10 min",
    servings: 2,
    description: "Tortilla filled with eggs and vegetables.",
    ingredients: ["2 tortillas", "4 eggs", "bell pepper", "cheese", "salt", "pepper"],
    steps: ["Cook eggs with chopped pepper.", "Warm tortillas.", "Add egg mixture and cheese.", "Roll tightly.", "Serve warm."]
  },
  {
    id: 61,
    slug: "grilled-salmon",
    title: "Grilled Salmon",
    category: "Dinner",
    image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=1200&q=80",
    prepTime: "10 min",
    cookTime: "12 min",
    servings: 2,
    description: "Simple grilled salmon with lemon.",
    ingredients: ["2 salmon fillets", "olive oil", "lemon", "salt", "pepper"],
    steps: ["Season salmon with oil, salt, and pepper.", "Grill or pan-sear until cooked.", "Turn once carefully.", "Add lemon juice.", "Serve immediately."]
  },
  {
    id: 62,
    slug: "roast-chicken",
    title: "Roast Chicken",
    category: "Dinner",
    image: "https://images.unsplash.com/photo-1518492104633-130d0cc84637?auto=format&fit=crop&w=1200&q=80",
    prepTime: "15 min",
    cookTime: "1 hr 10 min",
    servings: 4,
    description: "Whole oven-roasted chicken with herbs.",
    ingredients: ["1 whole chicken", "olive oil", "garlic", "paprika", "salt", "pepper", "herbs"],
    steps: ["Rub chicken with oil, garlic, herbs, and spices.", "Place in roasting pan.", "Roast until golden and cooked through.", "Rest before carving.", "Serve with vegetables."]
  },
  {
    id: 63,
    slug: "beef-stir-fry",
    title: "Beef Stir-Fry",
    category: "Dinner",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=1200&q=80",
    prepTime: "15 min",
    cookTime: "12 min",
    servings: 4,
    description: "Quick beef strips cooked with vegetables.",
    ingredients: ["400 g beef strips", "1 bell pepper", "1 onion", "soy sauce", "oil", "garlic"],
    steps: ["Heat oil in a large pan.", "Cook beef quickly until browned.", "Add vegetables and garlic.", "Stir in soy sauce.", "Serve hot with rice."]
  },
  {
    id: 64,
    slug: "baked-fish",
    title: "Baked Fish Fillets",
    category: "Dinner",
    image: "https://images.unsplash.com/photo-1510130387422-82bed34b37e9?auto=format&fit=crop&w=1200&q=80",
    prepTime: "10 min",
    cookTime: "20 min",
    servings: 4,
    description: "Tender baked fish with lemon and herbs.",
    ingredients: ["4 fish fillets", "olive oil", "lemon", "garlic", "parsley", "salt", "pepper"],
    steps: ["Place fish in baking dish.", "Top with oil, lemon, garlic, and herbs.", "Season well.", "Bake until flaky.", "Serve warm."]
  },
  {
    id: 65,
    slug: "chicken-rice",
    title: "Chicken and Rice",
    category: "Dinner",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=1200&q=80",
    prepTime: "15 min",
    cookTime: "30 min",
    servings: 4,
    description: "Simple one-pot chicken and rice.",
    ingredients: ["2 chicken breasts", "1 cup rice", "1 onion", "2 cups stock", "oil", "salt", "pepper"],
    steps: ["Brown chicken lightly and set aside.", "Cook onion in same pan.", "Add rice and stock.", "Return chicken and cover.", "Cook until rice is tender."]
  },
  {
    id: 66,
    slug: "meatballs-tomato-sauce",
    title: "Meatballs in Tomato Sauce",
    category: "Dinner",
    image: "https://images.unsplash.com/photo-1529563021893-cc83c992d75d?auto=format&fit=crop&w=1200&q=80",
    prepTime: "20 min",
    cookTime: "25 min",
    servings: 4,
    description: "Juicy meatballs simmered in tomato sauce.",
    ingredients: ["500 g ground beef", "1 onion", "breadcrumbs", "1 egg", "tomato sauce", "salt", "pepper"],
    steps: ["Mix beef with onion, breadcrumbs, egg, and seasoning.", "Shape meatballs.", "Brown lightly in a pan.", "Add tomato sauce and simmer.", "Serve with rice or pasta."]
  },
  {
    id: 67,
    slug: "shepherds-pie",
    title: "Shepherd's Pie",
    category: "Dinner",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=80",
    prepTime: "25 min",
    cookTime: "35 min",
    servings: 6,
    description: "Savory meat filling topped with mashed potato.",
    ingredients: ["500 g ground meat", "1 onion", "1 carrot", "mashed potatoes", "stock", "salt", "pepper"],
    steps: ["Cook meat with onion and carrot.", "Season and cook until mixture is rich.", "Spread into baking dish.", "Top with mashed potatoes.", "Bake until golden."]
  },
  {
    id: 68,
    slug: "chicken-curry",
    title: "Chicken Curry",
    category: "Dinner",
    image: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=1200&q=80",
    prepTime: "15 min",
    cookTime: "30 min",
    servings: 4,
    description: "Easy chicken curry with warming spices.",
    ingredients: ["500 g chicken", "1 onion", "2 garlic cloves", "curry powder", "tomato", "coconut milk or water", "oil"],
    steps: ["Cook onion and garlic in oil.", "Add chicken and curry powder.", "Add tomato and liquid.", "Simmer until chicken is cooked.", "Serve with rice."]
  },
  {
    id: 69,
    slug: "beef-tacos",
    title: "Beef Tacos",
    category: "Dinner",
    image: "https://images.unsplash.com/photo-1552332386-f8dd00dc2f85?auto=format&fit=crop&w=1200&q=80",
    prepTime: "15 min",
    cookTime: "15 min",
    servings: 4,
    description: "Tacos filled with seasoned beef and vegetables.",
    ingredients: ["8 taco shells", "300 g ground beef", "lettuce", "tomato", "cheese", "taco seasoning"],
    steps: ["Cook beef with seasoning.", "Warm taco shells.", "Fill with beef.", "Add lettuce, tomato, and cheese.", "Serve immediately."]
  },
  {
    id: 70,
    slug: "stuffed-zucchini",
    title: "Stuffed Zucchini Boats",
    category: "Dinner",
    image: "https://images.unsplash.com/photo-1543332164-6e82f355badc?auto=format&fit=crop&w=1200&q=80",
    prepTime: "20 min",
    cookTime: "25 min",
    servings: 4,
    description: "Zucchini halves filled with meat or vegetable mixture.",
    ingredients: ["4 zucchini", "ground meat or cooked rice", "1 onion", "tomato sauce", "cheese optional"],
    steps: ["Halve zucchini and scoop out centers.", "Prepare filling with onion and chosen base.", "Fill zucchini boats.", "Top with sauce and optional cheese.", "Bake until zucchini is tender."]
  },
  {
    id: 71,
    slug: "lentil-soup",
    title: "Red Lentil Soup",
    category: "Soup",
    image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=1200&q=80",
    prepTime: "10 min",
    cookTime: "25 min",
    servings: 4,
    description: "Smooth comforting red lentil soup.",
    ingredients: ["1 cup red lentils", "1 onion", "1 carrot", "stock", "olive oil", "salt", "pepper", "cumin"],
    steps: ["Cook onion and carrot in oil.", "Add lentils and stock.", "Simmer until soft.", "Blend until smooth if desired.", "Season and serve."]
  },
  {
    id: 72,
    slug: "tomato-soup",
    title: "Creamy Tomato Soup",
    category: "Soup",
    image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=1200&q=80",
    prepTime: "10 min",
    cookTime: "25 min",
    servings: 4,
    description: "Simple tomato soup with a smooth texture.",
    ingredients: ["6 tomatoes", "1 onion", "2 garlic cloves", "olive oil", "cream optional", "salt", "pepper"],
    steps: ["Cook onion and garlic in oil.", "Add tomatoes and simmer until soft.", "Blend until smooth.", "Add cream if desired.", "Season and serve."]
  },
  {
    id: 73,
    slug: "chicken-noodle-soup",
    title: "Chicken Noodle Soup",
    category: "Soup",
    image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=1200&q=80",
    prepTime: "15 min",
    cookTime: "30 min",
    servings: 4,
    description: "Classic soup with chicken, noodles, and vegetables.",
    ingredients: ["1 chicken breast", "1 carrot", "1 onion", "noodles", "stock", "salt", "pepper"],
    steps: ["Cook onion and carrot in stock.", "Add chicken and simmer until cooked.", "Shred chicken and return to pot.", "Add noodles.", "Cook until noodles are tender."]
  },
  {
    id: 74,
    slug: "pumpkin-soup",
    title: "Pumpkin Soup",
    category: "Soup",
    image: "https://images.unsplash.com/photo-1511690743698-d9d85f2fbf38?auto=format&fit=crop&w=1200&q=80",
    prepTime: "15 min",
    cookTime: "30 min",
    servings: 4,
    description: "Smooth pumpkin soup with warm spices.",
    ingredients: ["500 g pumpkin", "1 onion", "stock", "olive oil", "salt", "pepper", "cream optional"],
    steps: ["Cook onion in oil.", "Add pumpkin cubes and stock.", "Simmer until soft.", "Blend until smooth.", "Add cream if desired and serve."]
  },
  {
    id: 75,
    slug: "broccoli-soup",
    title: "Broccoli Soup",
    category: "Soup",
    image: "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=1200&q=80",
    prepTime: "10 min",
    cookTime: "20 min",
    servings: 4,
    description: "Green broccoli soup with a velvety texture.",
    ingredients: ["1 broccoli head", "1 onion", "stock", "olive oil", "salt", "pepper"],
    steps: ["Cook onion in oil.", "Add broccoli and stock.", "Simmer until tender.", "Blend until smooth.", "Season and serve warm."]
  },
  {
    id: 76,
    slug: "potato-leek-soup",
    title: "Potato Leek Soup",
    category: "Soup",
    image: "https://images.unsplash.com/photo-1511690743698-d9d85f2fbf38?auto=format&fit=crop&w=1200&q=80",
    prepTime: "15 min",
    cookTime: "30 min",
    servings: 4,
    description: "Comforting soup made with potatoes and leeks.",
    ingredients: ["2 leeks", "3 potatoes", "stock", "butter or oil", "salt", "pepper"],
    steps: ["Cook sliced leeks in butter or oil.", "Add potatoes and stock.", "Simmer until soft.", "Blend if desired.", "Season and serve."]
  },
  {
    id: 77,
    slug: "caesar-salad",
    title: "Caesar Salad",
    category: "Salad",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1200&q=80",
    prepTime: "15 min",
    cookTime: "10 min",
    servings: 4,
    description: "Crisp romaine with croutons and creamy dressing.",
    ingredients: ["romaine lettuce", "croutons", "parmesan", "caesar dressing", "chicken optional"],
    steps: ["Wash and chop lettuce.", "Toss with dressing.", "Add croutons and parmesan.", "Top with chicken if desired.", "Serve immediately."]
  },
  {
    id: 78,
    slug: "coleslaw",
    title: "Coleslaw",
    category: "Salad",
    image: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&w=1200&q=80",
    prepTime: "10 min",
    cookTime: "0 min",
    servings: 4,
    description: "Crunchy cabbage salad with creamy dressing.",
    ingredients: ["cabbage", "carrot", "mayonnaise", "lemon juice or vinegar", "salt", "pepper"],
    steps: ["Shred cabbage and carrot.", "Mix dressing ingredients.", "Combine vegetables with dressing.", "Taste and adjust seasoning.", "Chill before serving."]
  },
  {
    id: 79,
    slug: "potato-salad",
    title: "Potato Salad",
    category: "Salad",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1200&q=80",
    prepTime: "15 min",
    cookTime: "20 min",
    servings: 4,
    description: "Creamy potato salad for lunch or side dish.",
    ingredients: ["4 potatoes", "mayonnaise", "mustard", "parsley", "salt", "pepper"],
    steps: ["Boil potatoes until tender and cool.", "Cut into chunks.", "Mix with mayonnaise and mustard.", "Add parsley and seasoning.", "Serve chilled."]
  },
  {
    id: 80,
    slug: "tabbouleh",
    title: "Tabbouleh",
    category: "Salad",
    image: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&w=1200&q=80",
    prepTime: "20 min",
    cookTime: "10 min",
    servings: 4,
    description: "Herb-rich salad with bulgur, tomato, and lemon.",
    ingredients: ["1/2 cup bulgur", "parsley", "mint", "2 tomatoes", "1 onion", "olive oil", "lemon juice", "salt"],
    steps: ["Soak or cook bulgur and cool.", "Chop herbs and vegetables finely.", "Mix with bulgur.", "Dress with oil and lemon.", "Serve fresh."]
  },
  {
    id: 81,
    slug: "cucumber-yogurt-salad",
    title: "Cucumber Yogurt Salad",
    category: "Salad",
    image: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&w=1200&q=80",
    prepTime: "10 min",
    cookTime: "0 min",
    servings: 4,
    description: "Cool cucumber salad with yogurt and herbs.",
    ingredients: ["2 cucumbers", "1 cup yogurt", "mint or dill", "salt", "pepper"],
    steps: ["Chop cucumbers.", "Mix yogurt with herbs and seasoning.", "Add cucumbers.", "Chill briefly.", "Serve cold."]
  },
  {
    id: 82,
    slug: "beet-salad",
    title: "Beet Salad",
    category: "Salad",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1200&q=80",
    prepTime: "15 min",
    cookTime: "35 min",
    servings: 4,
    description: "Colorful beet salad with lemon dressing.",
    ingredients: ["3 beets", "olive oil", "lemon juice", "parsley", "salt", "pepper"],
    steps: ["Cook or roast beets until tender.", "Peel and dice.", "Mix with oil, lemon, and parsley.", "Season well.", "Serve chilled or room temperature."]
  },
  {
    id: 83,
    slug: "garlic-bread",
    title: "Garlic Bread",
    category: "Sides",
    image: "https://images.unsplash.com/photo-1506280754576-f6fa8a873550?auto=format&fit=crop&w=1200&q=80",
    prepTime: "10 min",
    cookTime: "10 min",
    servings: 4,
    description: "Toasted bread with garlic butter.",
    ingredients: ["baguette", "butter", "2 garlic cloves", "parsley"],
    steps: ["Mix softened butter with garlic and parsley.", "Spread on bread slices.", "Bake until golden.", "Serve warm."]
  },
  {
    id: 84,
    slug: "mashed-potatoes",
    title: "Mashed Potatoes",
    category: "Sides",
    image: "https://images.unsplash.com/photo-1543332164-6e82f355badc?auto=format&fit=crop&w=1200&q=80",
    prepTime: "10 min",
    cookTime: "20 min",
    servings: 4,
    description: "Smooth creamy mashed potatoes.",
    ingredients: ["4 potatoes", "butter", "milk", "salt", "pepper"],
    steps: ["Boil potatoes until soft.", "Drain and mash.", "Add butter and milk.", "Season to taste.", "Serve warm."]
  },
  {
    id: 85,
    slug: "roasted-vegetables",
    title: "Roasted Vegetables",
    category: "Sides",
    image: "https://images.unsplash.com/photo-1543332164-6e82f355badc?auto=format&fit=crop&w=1200&q=80",
    prepTime: "10 min",
    cookTime: "25 min",
    servings: 4,
    description: "Mixed vegetables roasted until caramelized.",
    ingredients: ["carrot", "zucchini", "pepper", "onion", "olive oil", "salt", "pepper"],
    steps: ["Cut vegetables evenly.", "Toss with oil and seasoning.", "Spread on a tray.", "Roast until tender.", "Serve warm."]
  },
  {
    id: 86,
    slug: "rice-pilaf",
    title: "Rice Pilaf",
    category: "Sides",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=1200&q=80",
    prepTime: "10 min",
    cookTime: "20 min",
    servings: 4,
    description: "Fluffy seasoned rice cooked in stock.",
    ingredients: ["1 cup rice", "2 cups stock", "1 tbsp butter or oil", "salt"],
    steps: ["Rinse rice.", "Heat butter and add rice briefly.", "Pour in stock.", "Cover and cook until tender.", "Fluff before serving."]
  },
  {
    id: 87,
    slug: "buttered-green-beans",
    title: "Buttered Green Beans",
    category: "Sides",
    image: "https://images.unsplash.com/photo-1543332164-6e82f355badc?auto=format&fit=crop&w=1200&q=80",
    prepTime: "10 min",
    cookTime: "10 min",
    servings: 4,
    description: "Simple green beans sautéed with butter.",
    ingredients: ["300 g green beans", "butter", "salt", "pepper"],
    steps: ["Boil or steam green beans until tender-crisp.", "Drain well.", "Toss in butter.", "Season and serve."]
  },
  {
    id: 88,
    slug: "corn-on-the-cob",
    title: "Corn on the Cob",
    category: "Sides",
    image: "https://images.unsplash.com/photo-1551754655-cd27e38d2076?auto=format&fit=crop&w=1200&q=80",
    prepTime: "5 min",
    cookTime: "12 min",
    servings: 4,
    description: "Boiled or grilled corn served with butter.",
    ingredients: ["4 corn cobs", "butter", "salt"],
    steps: ["Boil or grill corn until tender.", "Brush with butter.", "Season lightly.", "Serve warm."]
  },
  {
    id: 89,
    slug: "sauteed-spinach",
    title: "Sautéed Spinach",
    category: "Sides",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1200&q=80",
    prepTime: "5 min",
    cookTime: "5 min",
    servings: 4,
    description: "Quick garlic spinach side dish.",
    ingredients: ["300 g spinach", "1 garlic clove", "olive oil", "salt"],
    steps: ["Heat oil and garlic briefly.", "Add spinach.", "Cook until wilted.", "Season and serve."]
  },
  {
    id: 90,
    slug: "herb-couscous",
    title: "Herb Couscous",
    category: "Sides",
    image: "https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1200&q=80",
    prepTime: "10 min",
    cookTime: "10 min",
    servings: 4,
    description: "Light fluffy couscous with herbs.",
    ingredients: ["1 cup couscous", "1 cup hot water or stock", "parsley", "olive oil", "salt"],
    steps: ["Pour hot liquid over couscous.", "Cover 5 minutes.", "Fluff with fork.", "Add herbs and oil.", "Serve warm."]
  },
  {
    id: 91,
    slug: "orange-juice",
    title: "Fresh Orange Juice",
    category: "Drinks",
    image: "https://images.unsplash.com/photo-1613478223719-2ab802602423?auto=format&fit=crop&w=1200&q=80",
    prepTime: "5 min",
    cookTime: "0 min",
    servings: 2,
    description: "Simple freshly squeezed orange juice.",
    ingredients: ["4 oranges"],
    steps: ["Wash and cut oranges.", "Juice them.", "Serve immediately cold."]
  },
  {
    id: 92,
    slug: "mint-tea",
    title: "Moroccan Mint Tea",
    category: "Drinks",
    image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=80",
    prepTime: "5 min",
    cookTime: "10 min",
    servings: 4,
    description: "Sweet green tea with fresh mint.",
    ingredients: ["1 tsp green tea", "fresh mint", "sugar to taste", "hot water"],
    steps: ["Rinse tea leaves quickly.", "Add tea, mint, sugar, and hot water to teapot.", "Let steep briefly.", "Pour and aerate by pouring from height.", "Serve hot."]
  },
  {
    id: 93,
    slug: "iced-coffee",
    title: "Iced Coffee",
    category: "Drinks",
    image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=80",
    prepTime: "5 min",
    cookTime: "0 min",
    servings: 2,
    description: "Cold coffee drink with milk and ice.",
    ingredients: ["1 cup brewed coffee cooled", "milk", "ice", "sugar optional"],
    steps: ["Fill glasses with ice.", "Pour in coffee.", "Add milk and sugar if desired.", "Stir and serve."]
  },
  {
    id: 94,
    slug: "lemonade",
    title: "Classic Lemonade",
    category: "Drinks",
    image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=1200&q=80",
    prepTime: "10 min",
    cookTime: "0 min",
    servings: 4,
    description: "Refreshing lemonade for warm days.",
    ingredients: ["4 lemons", "water", "sugar", "ice"],
    steps: ["Squeeze lemons.", "Mix juice with water and sugar.", "Taste and adjust.", "Serve over ice."]
  },
  {
    id: 95,
    slug: "mango-lassi",
    title: "Mango Lassi",
    category: "Drinks",
    image: "https://images.unsplash.com/photo-1502741338009-cac2772e18bc?auto=format&fit=crop&w=1200&q=80",
    prepTime: "5 min",
    cookTime: "0 min",
    servings: 2,
    description: "Creamy mango yogurt drink.",
    ingredients: ["1 mango", "1 cup yogurt", "1/2 cup milk", "1 tsp honey"],
    steps: ["Blend mango, yogurt, milk, and honey.", "Pour into glasses.", "Serve cold."]
  },
  {
    id: 96,
    slug: "strawberry-milkshake",
    title: "Strawberry Milkshake",
    category: "Drinks",
    image: "https://images.unsplash.com/photo-1553530666-ba11a90bb918?auto=format&fit=crop&w=1200&q=80",
    prepTime: "5 min",
    cookTime: "0 min",
    servings: 2,
    description: "Sweet strawberry shake with milk.",
    ingredients: ["1 cup strawberries", "1 cup milk", "ice cream optional", "sugar optional"],
    steps: ["Blend strawberries with milk.", "Add ice cream if using.", "Blend smooth.", "Serve cold."]
  },
  {
    id: 97,
    slug: "hot-chocolate",
    title: "Hot Chocolate",
    category: "Drinks",
    image: "https://images.unsplash.com/photo-1517578239113-b03992dcdd25?auto=format&fit=crop&w=1200&q=80",
    prepTime: "5 min",
    cookTime: "10 min",
    servings: 2,
    description: "Warm chocolate drink for cold days.",
    ingredients: ["2 cups milk", "2 tbsp cocoa powder", "2 tbsp sugar", "dark chocolate optional"],
    steps: ["Heat milk gently.", "Whisk in cocoa and sugar.", "Add chocolate if desired.", "Pour into mugs and serve."]
  },
  {
    id: 98,
    slug: "cucumber-mint-water",
    title: "Cucumber Mint Water",
    category: "Drinks",
    image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=1200&q=80",
    prepTime: "5 min",
    cookTime: "0 min",
    servings: 4,
    description: "Infused water with cucumber and mint.",
    ingredients: ["1 cucumber", "mint leaves", "1 liter water", "ice"],
    steps: ["Slice cucumber.", "Add to jug with mint.", "Pour over water and ice.", "Chill before serving."]
  },
  {
    id: 99,
    slug: "oreo-shake",
    title: "Oreo Shake",
    category: "Drinks",
    image: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=1200&q=80",
    prepTime: "5 min",
    cookTime: "0 min",
    servings: 2,
    description: "Creamy cookies and cream style milkshake.",
    ingredients: ["6 chocolate sandwich cookies", "1 cup milk", "2 scoops vanilla ice cream"],
    steps: ["Blend cookies with milk and ice cream.", "Pour into glasses.", "Serve cold."]
  },
  {
    id: 100,
    slug: "watermelon-juice",
    title: "Watermelon Juice",
    category: "Drinks",
    image: "https://images.unsplash.com/photo-1502741338009-cac2772e18bc?auto=format&fit=crop&w=1200&q=80",
    prepTime: "10 min",
    cookTime: "0 min",
    servings: 4,
    description: "Cool refreshing watermelon juice.",
    ingredients: ["4 cups watermelon cubes", "lime juice optional", "ice"],
    steps: ["Blend watermelon until smooth.", "Strain if desired.", "Add lime juice and ice.", "Serve cold."]
  },
  {
    id: 101,
    slug: "white-rice",
    title: "Steamed White Rice",
    category: "Basics",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=1200&q=80",
    prepTime: "5 min",
    cookTime: "18 min",
    servings: 4,
    description: "Basic fluffy white rice.",
    ingredients: ["1 cup rice", "2 cups water", "salt optional"],
    steps: ["Rinse rice.", "Bring rice and water to a boil.", "Cover and cook on low.", "Rest a few minutes.", "Fluff and serve."]
  },
  {
    id: 102,
    slug: "boiled-eggs",
    title: "Boiled Eggs",
    category: "Basics",
    image: "https://images.unsplash.com/photo-1482049016688-2d3e1b311543?auto=format&fit=crop&w=1200&q=80",
    prepTime: "2 min",
    cookTime: "10 min",
    servings: 2,
    description: "Simple boiled eggs for breakfast or snack.",
    ingredients: ["4 eggs", "water"],
    steps: ["Place eggs in a pot and cover with water.", "Bring to a boil.", "Cook to desired doneness.", "Cool in cold water and peel."]
  },
  {
    id: 103,
    slug: "grilled-cheese-sandwich",
    title: "Grilled Cheese Sandwich",
    category: "Basics",
    image: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=1200&q=80",
    prepTime: "5 min",
    cookTime: "8 min",
    servings: 2,
    description: "Golden toasted sandwich with melted cheese.",
    ingredients: ["4 bread slices", "cheese", "butter"],
    steps: ["Butter bread.", "Add cheese between slices.", "Cook in a pan until golden on both sides.", "Serve warm."]
  },
  {
    id: 104,
    slug: "roasted-potatoes",
    title: "Roasted Potatoes",
    category: "Basics",
    image: "https://images.unsplash.com/photo-1543332164-6e82f355badc?auto=format&fit=crop&w=1200&q=80",
    prepTime: "10 min",
    cookTime: "35 min",
    servings: 4,
    description: "Crisp roasted potato wedges.",
    ingredients: ["4 potatoes", "olive oil", "salt", "pepper", "paprika optional"],
    steps: ["Cut potatoes into wedges.", "Toss with oil and seasoning.", "Bake until golden and crisp.", "Serve warm."]
  },
  {
    id: 105,
    slug: "pasta-tomato-sauce",
    title: "Pasta with Tomato Sauce",
    category: "Basics",
    image: "https://images.unsplash.com/photo-1622973536968-3ead9e780960?auto=format&fit=crop&w=1200&q=80",
    prepTime: "10 min",
    cookTime: "15 min",
    servings: 4,
    description: "Easy pasta for beginners.",
    ingredients: ["300 g pasta", "tomato sauce", "1 garlic clove", "olive oil", "salt"],
    steps: ["Cook pasta.", "Warm sauce with garlic and oil.", "Combine pasta with sauce.", "Serve hot."]
  },
  {
    id: 106,
    slug: "baked-omelet",
    title: "Baked Omelet",
    category: "Basics",
    image: "https://images.unsplash.com/photo-1510693206972-df098062cb71?auto=format&fit=crop&w=1200&q=80",
    prepTime: "10 min",
    cookTime: "18 min",
    servings: 4,
    description: "Easy oven omelet with vegetables.",
    ingredients: ["6 eggs", "1 pepper", "cheese", "salt", "pepper"],
    steps: ["Whisk eggs with seasoning.", "Add chopped vegetables and cheese.", "Pour into dish.", "Bake until set.", "Slice and serve."]
  },
  {
    id: 107,
    slug: "garlic-butter-shrimp",
    title: "Garlic Butter Shrimp",
    category: "Seafood",
    image: "https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=1200&q=80",
    prepTime: "10 min",
    cookTime: "8 min",
    servings: 4,
    description: "Quick shrimp sautéed with garlic and butter.",
    ingredients: ["400 g shrimp", "2 garlic cloves", "butter", "lemon", "parsley", "salt", "pepper"],
    steps: ["Melt butter with garlic.", "Add shrimp and cook until pink.", "Season with salt, pepper, and lemon.", "Top with parsley and serve."]
  },
  {
    id: 108,
    slug: "tuna-salad-sandwich",
    title: "Tuna Salad Sandwich",
    category: "Lunch",
    image: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=1200&q=80",
    prepTime: "10 min",
    cookTime: "0 min",
    servings: 2,
    description: "Easy tuna sandwich for lunch.",
    ingredients: ["1 can tuna", "mayonnaise", "lemon juice", "bread", "lettuce"],
    steps: ["Mix tuna with mayonnaise and lemon.", "Spread onto bread.", "Add lettuce.", "Close sandwich and serve."]
  },
  {
    id: 109,
    slug: "mac-and-cheese",
    title: "Mac and Cheese",
    category: "Comfort Food",
    image: "https://images.unsplash.com/photo-1543332164-6e82f355badc?auto=format&fit=crop&w=1200&q=80",
    prepTime: "10 min",
    cookTime: "20 min",
    servings: 4,
    description: "Creamy macaroni with melted cheese sauce.",
    ingredients: ["300 g macaroni", "butter", "2 tbsp flour", "2 cups milk", "grated cheese", "salt", "pepper"],
    steps: ["Cook macaroni.", "Make a sauce with butter, flour, and milk.", "Add cheese until melted.", "Mix with macaroni.", "Serve hot or bake briefly."]
  },
  {
    id: 110,
    slug: "fried-rice",
    title: "Vegetable Fried Rice",
    category: "Asian",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=1200&q=80",
    prepTime: "10 min",
    cookTime: "12 min",
    servings: 4,
    description: "Quick fried rice with vegetables and soy sauce.",
    ingredients: ["3 cups cooked rice", "1 carrot", "peas", "1 egg optional", "soy sauce", "oil"],
    steps: ["Heat oil in a wok or pan.", "Cook vegetables until just tender.", "Add rice and stir well.", "Season with soy sauce.", "Add egg if using and serve hot."]
  }
];

window.recipesData = recipesData;
